# Generated by Django 6.0.5 on 2026-06-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Software', 'Software'), ('Equipment', 'Equipment'), ('Internet', 'Internet'), ('Office Supplies', 'Office Supplies'), ('Mileage', 'Mileage'), ('Advertising', 'Advertising'), ('Education', 'Education'), ('Travel', 'Travel'), ('Other', 'Other')], max_length=100),
        ),
    ]
